use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

#[test]
fn builds_generated_ron_from_wasm_component() {
    let fixture_dir =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/minimal_guest");

    let status = Command::new("cargo")
        .current_dir(&fixture_dir)
        .args(["build", "--target", "wasm32-wasip2"])
        .status()
        .expect("failed to invoke cargo build for fixture guest");

    assert!(status.success(), "fixture guest should build successfully");

    let component_path = fixture_dir.join("target/wasm32-wasip2/debug/vessel_test_guest.wasm");
    assert!(
        component_path.exists(),
        "fixture wasm component should exist"
    );

    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock should be after unix epoch")
        .as_nanos();
    let output_dir = std::env::temp_dir().join(format!("vessel_component_build_{unique}"));
    let _ = fs::remove_dir_all(&output_dir);

    let summary = vessel::build_component(&component_path, &output_dir)
        .expect("vessel host should build files from the wasm component");

    assert_eq!(
        summary.written_files, 1,
        "expected exactly one generated file"
    );

    let output_path = output_dir.join("example/test.ron");
    assert!(output_path.exists(), "generated ron file should exist");

    let content = fs::read_to_string(&output_path).expect("generated file should be readable");
    assert!(
        content.contains("Generated by Vessel"),
        "generated file should include vessel header"
    );
    assert!(
        content.contains("fixture"),
        "generated file should contain fixture payload"
    );

    let _ = fs::remove_dir_all(&output_dir);
}
