//! File output — writes RON strings to disk.
//!
//! 文件输出 — 将 RON 字符串写入磁盘。

use crate::component_host::GeneratedRonFile;
use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Component, Path, PathBuf};

const DEFAULT_GENERATED_FILE_HEADER: &str = r#"// =============================================================================
// BOOTSTRAPPED BY VESSEL
// =============================================================================
// This file was initially generated by Vessel to provide a baseline structure.
//
// [ MANUAL EDITS ALLOWED - PROCEED WITH CAUTION ]
// You can modify this file to suit your specific needs. However,
// be aware that regenerating this module via Vessel will OVERWRITE this file.
//
// GUIDELINES FOR MODIFICATION:
// 1. SAFETY FIRST: Ensure your current state is committed to version control
//    (e.g., Git) before making changes, so you can easily revert or handle
//    future merge conflicts.
// 2. THE "PROPER" WAY: If your goal is to change the underlying logic or
//    structure globally, please edit the Vessel source schema/configuration
//    instead of modifying this file directly.
// ============================================================================="#;

const OUTPUT_MANIFEST_RELATIVE_PATH: &str = ".build/vessel-output-manifest.toml";
const OUTPUT_MANIFEST_VERSION: u32 = 1;
const FORBIDDEN_OUTPUT_ROOTS: &[&str] = &[
    ".build", ".git", ".idea", ".vscode", "content", "runtime", "target",
];

#[derive(Debug, Deserialize, Default)]
#[serde(default)]
struct ProjectFile {
    content_library: ContentLibraryConfig,
}

#[derive(Debug, Deserialize, Default)]
#[serde(default)]
struct ContentLibraryConfig {
    generated_file_header: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
#[serde(default)]
struct OutputManifest {
    version: u32,
    owned_paths: Vec<String>,
}

#[derive(Debug)]
struct OutputConfig {
    manifest_path: PathBuf,
    generated_file_header: String,
}

impl OutputConfig {
    fn load(project_root: &Path) -> Result<Self> {
        let mod_toml = project_root.join("mod.toml");
        let generated_file_header = if mod_toml.exists() {
            let contents = fs::read_to_string(&mod_toml)
                .with_context(|| format!("failed to read project file: {}", mod_toml.display()))?;
            let parsed: ProjectFile = toml::from_str(&contents)
                .with_context(|| format!("failed to parse project file: {}", mod_toml.display()))?;
            parsed
                .content_library
                .generated_file_header
                .unwrap_or_else(|| DEFAULT_GENERATED_FILE_HEADER.to_owned())
        } else {
            DEFAULT_GENERATED_FILE_HEADER.to_owned()
        };

        Ok(Self {
            manifest_path: project_root.join(OUTPUT_MANIFEST_RELATIVE_PATH),
            generated_file_header,
        })
    }

    fn validate_generated_paths(&self, files: &[GeneratedRonFile]) -> Result<()> {
        for file in files {
            let relative = normalized_relative_path(&file.path)?;
            if !relative.ends_with(".ron") {
                return Err(anyhow!("generated path '{}' must end with .ron", relative));
            }

            let first_segment = relative
                .split('/')
                .next()
                .expect("normalized relative path should contain at least one segment");
            if FORBIDDEN_OUTPUT_ROOTS.contains(&first_segment) {
                return Err(anyhow!(
                    "generated path '{}' is not allowed under tooling/source root '{}'",
                    relative,
                    first_segment
                ));
            }
        }

        Ok(())
    }

    fn prune_stale_files(&self, files: &[GeneratedRonFile], output_dir: &Path) -> Result<()> {
        let previous = self.load_manifest()?;
        let expected_paths: BTreeSet<String> = files
            .iter()
            .map(|file| normalized_relative_path(&file.path))
            .collect::<Result<_>>()?;

        for previous_path in previous.owned_paths {
            let relative =
                normalized_relative_path(Path::new(&previous_path)).with_context(|| {
                    format!(
                        "invalid path '{}' found in vessel output manifest {}",
                        previous_path,
                        self.manifest_path.display()
                    )
                })?;
            if expected_paths.contains(&relative) {
                continue;
            }

            let path = output_dir.join(&relative);
            if !path.exists() {
                continue;
            }
            if !path.is_file() {
                return Err(anyhow!(
                    "previously owned path '{}' is not a file",
                    path.display()
                ));
            }

            fs::remove_file(&path).with_context(|| {
                format!("failed to remove stale generated file: {}", path.display())
            })?;
        }

        Ok(())
    }

    fn write_manifest(&self, files: &[GeneratedRonFile]) -> Result<()> {
        let owned_paths = files
            .iter()
            .map(|file| normalized_relative_path(&file.path))
            .collect::<Result<Vec<_>>>()?;

        let manifest = OutputManifest {
            version: OUTPUT_MANIFEST_VERSION,
            owned_paths,
        };
        let serialized = toml::to_string_pretty(&manifest)
            .context("failed to serialize vessel output manifest")?;

        if let Some(parent) = self.manifest_path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create directory: {}", parent.display()))?;
        }
        fs::write(&self.manifest_path, serialized).with_context(|| {
            format!(
                "failed to write vessel output manifest: {}",
                self.manifest_path.display()
            )
        })?;

        Ok(())
    }

    fn load_manifest(&self) -> Result<OutputManifest> {
        if !self.manifest_path.exists() {
            return Ok(OutputManifest::default());
        }

        let contents = fs::read_to_string(&self.manifest_path).with_context(|| {
            format!(
                "failed to read vessel output manifest: {}",
                self.manifest_path.display()
            )
        })?;
        let manifest: OutputManifest = toml::from_str(&contents).with_context(|| {
            format!(
                "failed to parse vessel output manifest: {}",
                self.manifest_path.display()
            )
        })?;

        if manifest.version != OUTPUT_MANIFEST_VERSION {
            return Err(anyhow!(
                "unsupported vessel output manifest version {} in {}",
                manifest.version,
                self.manifest_path.display()
            ));
        }

        Ok(manifest)
    }

    fn render_output_text(&self, ron_text: &str) -> String {
        let body = ron_text.trim_end_matches(['\n', '\r']);
        let header = self.generated_file_header.trim_end_matches(['\n', '\r']);
        if header.is_empty() {
            return format!("{body}\n");
        }
        format!("{header}\n\n{body}\n")
    }
}

fn normalized_relative_path(path: &Path) -> Result<String> {
    if path.is_absolute() {
        return Err(anyhow!(
            "generated path must be relative: {}",
            path.display()
        ));
    }

    let mut parts = Vec::new();
    for component in path.components() {
        match component {
            Component::Normal(part) => parts.push(part.to_string_lossy().into_owned()),
            Component::CurDir => {}
            Component::ParentDir => {
                return Err(anyhow!(
                    "generated path must not contain parent traversal: {}",
                    path.display()
                ));
            }
            Component::RootDir | Component::Prefix(_) => {
                return Err(anyhow!(
                    "generated path must be relative: {}",
                    path.display()
                ));
            }
        }
    }

    if parts.is_empty() {
        return Err(anyhow!("generated path must not be empty"));
    }

    Ok(parts.join("/"))
}

/// Write generated files emitted by a Vessel content component.
///
/// 写入 Vessel 内容组件发射的生成文件。
pub fn write_generated_files(files: &[GeneratedRonFile], output_dir: &Path) -> Result<()> {
    validate_unique_generated_paths(files)?;

    let output_config = OutputConfig::load(output_dir)?;
    output_config.validate_generated_paths(files)?;
    output_config.prune_stale_files(files, output_dir)?;

    for file in files {
        let relative = normalized_relative_path(&file.path)?;
        let full = output_dir.join(&relative);
        if let Some(parent) = full.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("failed to create directory: {}", parent.display()))?;
        }
        let rendered_text = output_config.render_output_text(&file.ron_text);
        fs::write(&full, rendered_text)
            .with_context(|| format!("failed to write: {}", full.display()))?;
    }

    output_config.write_manifest(files)?;
    Ok(())
}

fn validate_unique_generated_paths(files: &[GeneratedRonFile]) -> Result<()> {
    let mut seen = BTreeSet::new();

    for file in files {
        let relative = normalized_relative_path(&file.path)?;
        if !seen.insert(relative.clone()) {
            return Err(anyhow!(
                "generated file '{}' was emitted more than once",
                relative
            ));
        }
    }

    Ok(())
}
